/**
 * Electric - Electric Piano Physical Modeling Instrument
 * 
 * Based on Ableton Electric device - emulates Rhodes, Wurlitzer, and Pianet
 * electric pianos using physical modeling techniques.
 */

// ============================================================================
// MODEL TYPES
// ============================================================================

export type PianoModel = 'rhodes' | 'wurlitzer' | 'pianet';

// ============================================================================
// PICKUP SECTION
// ============================================================================

export type PickupType = 'fm' | 'em';

export interface PickupParams {
  /** Pickup symmetry/position (-1 to 1) */
  symmetry: number;
  /** Distance from tine/bar (0-1) */
  distance: number;
  /** Pickup type: FM (field coil) or EM (electromagnetic) */
  type: PickupType;
  /** Output level from pickup (0-1) */
  level: number;
}

// ============================================================================
// TINE / BAR SECTION
// ============================================================================

export interface TineParams {
  /** Tonal character of the tine/bar (0-1) */
  tone: number;
  /** Harmonic content/color (0-1) */
  color: number;
  /** Decay time of the tine vibration (0.01-5s) */
  decay: number;
  /** Output level (0-1) */
  level: number;
  /** Inharmonicity factor (0-1) */
  inharmonics: number;
}

// ============================================================================
// DAMPER SECTION
// ============================================================================

export interface DamperParams {
  /** Damper engagement amount (0-1) */
  amount: number;
  /** Damper tone character (0-1) */
  tone: number;
  /** Noise generated by damper (0-1) */
  noise: number;
}

// ============================================================================
// HAMMER SECTION
// ============================================================================

export interface HammerParams {
  /** Hammer hardness/stiffness (0-1) */
  hardness: number;
  /** Amount of mechanical noise (0-1) */
  noise: number;
  /** Force/velocity response curve (0-1) */
  force: number;
}

// ============================================================================
// AMP SECTION
// ============================================================================

export interface AmpParams {
  /** Preamp drive/saturation (0-1) */
  drive: number;
  /** Tone/EQ control (0-1) */
  tone: number;
  /** Output level (0-1) */
  level: number;
}

// ============================================================================
// TREMOLO EFFECT
// ============================================================================

export type TremoloWaveform = 'sine' | 'triangle' | 'saw' | 'square';

export interface TremoloParams {
  enabled: boolean;
  /** Rate in Hz (0.1-20) */
  rate: number;
  /** Modulation depth (0-1) */
  amount: number;
  /** LFO waveform */
  waveform: TremoloWaveform;
  /** Stereo phase offset (0-180 degrees) */
  stereoPhase: number;
  /** Sync to tempo */
  sync: boolean;
  /** Sync division if synced */
  syncDivision?: number;
}

// ============================================================================
// CHORUS EFFECT
// ============================================================================

export interface ChorusParams {
  enabled: boolean;
  /** Rate in Hz (0.1-10) */
  rate: number;
  /** Modulation depth (0-1) */
  amount: number;
  /** Number of delay lines (1-3) */
  voices: number;
}

// ============================================================================
// GLOBAL PARAMETERS
// ============================================================================

export interface GlobalParams {
  /** Global transpose in semitones (-24 to +24) */
  transpose: number;
  /** Fine tuning in cents (-100 to +100) */
  fineTune: number;
  /** Stretch tuning amount (0-1) */
  stretch: number;
  /** Number of voices for polyphony (1-32) */
  voices: number;
  /** Master volume (0-1) */
  volume: number;
  /** Velocity curve (0.1-5, 1=linear) */
  velocityCurve: number;
}

// ============================================================================
// MIDI MAPPINGS
// ============================================================================

export interface MidiMappingParams {
  /** Pitch bend range in semitones */
  pitchBendRange: number;
  /** Mod wheel controls tremolo depth */
  modToTremolo: boolean;
  /** Aftertouch amount (0-1) */
  aftertouchAmount: number;
  /** Sustain pedal enabled */
  sustainPedal: boolean;
}

// ============================================================================
// COMPLETE INSTRUMENT STATE
// ============================================================================

export interface ElectricState {
  /** Piano model type */
  model: PianoModel;
  /** Pickup characteristics */
  pickup: PickupParams;
  /** Tine/bar physics */
  tine: TineParams;
  /** Damper behavior */
  damper: DamperParams;
  /** Hammer characteristics */
  hammer: HammerParams;
  /** Amplifier section */
  amp: AmpParams;
  /** Tremolo effect */
  tremolo: TremoloParams;
  /** Chorus effect */
  chorus: ChorusParams;
  /** Global settings */
  global: GlobalParams;
  /** MIDI mappings */
  midi: MidiMappingParams;
}

// ============================================================================
// MODEL PRESETS
// ============================================================================

export const rhodesPreset: Partial<ElectricState> = {
  model: 'rhodes',
  pickup: {
    symmetry: 0,
    distance: 0.4,
    type: 'em',
    level: 0.9,
  },
  tine: {
    tone: 0.6,
    color: 0.4,
    decay: 1.5,
    level: 1.0,
    inharmonics: 0.2,
  },
  damper: {
    amount: 0.8,
    tone: 0.5,
    noise: 0.1,
  },
  hammer: {
    hardness: 0.5,
    noise: 0.05,
    force: 0.7,
  },
  amp: {
    drive: 0.2,
    tone: 0.5,
    level: 0.8,
  },
  tremolo: {
    enabled: false,
    rate: 5,
    amount: 0.3,
    waveform: 'sine',
    stereoPhase: 0,
    sync: false,
  },
  chorus: {
    enabled: false,
    rate: 0.5,
    amount: 0.3,
    voices: 2,
  },
};

export const wurlitzerPreset: Partial<ElectricState> = {
  model: 'wurlitzer',
  pickup: {
    symmetry: 0.2,
    distance: 0.3,
    type: 'fm',
    level: 0.85,
  },
  tine: {
    tone: 0.4,
    color: 0.6,
    decay: 1.2,
    level: 1.0,
    inharmonics: 0.15,
  },
  damper: {
    amount: 0.9,
    tone: 0.4,
    noise: 0.15,
  },
  hammer: {
    hardness: 0.6,
    noise: 0.08,
    force: 0.6,
  },
  amp: {
    drive: 0.15,
    tone: 0.6,
    level: 0.75,
  },
  tremolo: {
    enabled: true,
    rate: 4,
    amount: 0.4,
    waveform: 'sine',
    stereoPhase: 90,
    sync: false,
  },
  chorus: {
    enabled: false,
    rate: 0.8,
    amount: 0.2,
    voices: 2,
  },
};

export const pianetPreset: Partial<ElectricState> = {
  model: 'pianet',
  pickup: {
    symmetry: -0.1,
    distance: 0.35,
    type: 'em',
    level: 0.8,
  },
  tine: {
    tone: 0.5,
    color: 0.5,
    decay: 1.0,
    level: 1.0,
    inharmonics: 0.1,
  },
  damper: {
    amount: 0.7,
    tone: 0.6,
    noise: 0.2,
  },
  hammer: {
    hardness: 0.4,
    noise: 0.1,
    force: 0.5,
  },
  amp: {
    drive: 0.25,
    tone: 0.4,
    level: 0.85,
  },
  tremolo: {
    enabled: false,
    rate: 3,
    amount: 0.2,
    waveform: 'triangle',
    stereoPhase: 0,
    sync: false,
  },
  chorus: {
    enabled: true,
    rate: 0.6,
    amount: 0.4,
    voices: 3,
  },
};

// ============================================================================
// DEFAULT STATE
// ============================================================================

export const defaultElectricState: ElectricState = {
  model: 'rhodes',
  pickup: rhodesPreset.pickup!,
  tine: rhodesPreset.tine!,
  damper: rhodesPreset.damper!,
  hammer: rhodesPreset.hammer!,
  amp: rhodesPreset.amp!,
  tremolo: rhodesPreset.tremolo!,
  chorus: rhodesPreset.chorus!,
  global: {
    transpose: 0,
    fineTune: 0,
    stretch: 0.1,
    voices: 16,
    volume: 0.8,
    velocityCurve: 1.0,
  },
  midi: {
    pitchBendRange: 2,
    modToTremolo: true,
    aftertouchAmount: 0.5,
    sustainPedal: true,
  },
};

// ============================================================================
// PARAMETER METADATA
// ============================================================================

export interface ParameterSpec {
  id: string;
  name: string;
  min: number;
  max: number;
  default: number;
  unit?: string;
  step?: number;
  type: 'float' | 'int' | 'enum' | 'bool';
  enumValues?: string[];
}

export const electricParameterSpecs: ParameterSpec[] = [
  // Model
  { id: 'model', name: 'Model', min: 0, max: 2, default: 0, type: 'enum', enumValues: ['rhodes', 'wurlitzer', 'pianet'] },
  // Pickup
  { id: 'pickup.symmetry', name: 'Pickup Symmetry', min: -1, max: 1, default: 0, type: 'float' },
  { id: 'pickup.distance', name: 'Pickup Distance', min: 0, max: 1, default: 0.4, type: 'float' },
  { id: 'pickup.level', name: 'Pickup Level', min: 0, max: 1, default: 0.9, type: 'float' },
  // Tine
  { id: 'tine.tone', name: 'Tine Tone', min: 0, max: 1, default: 0.6, type: 'float' },
  { id: 'tine.color', name: 'Tine Color', min: 0, max: 1, default: 0.4, type: 'float' },
  { id: 'tine.decay', name: 'Tine Decay', min: 0.01, max: 5, default: 1.5, unit: 's', type: 'float' },
  { id: 'tine.level', name: 'Tine Level', min: 0, max: 1, default: 1.0, type: 'float' },
  // Damper
  { id: 'damper.amount', name: 'Damper Amount', min: 0, max: 1, default: 0.8, type: 'float' },
  { id: 'damper.tone', name: 'Damper Tone', min: 0, max: 1, default: 0.5, type: 'float' },
  // Hammer
  { id: 'hammer.hardness', name: 'Hammer Hardness', min: 0, max: 1, default: 0.5, type: 'float' },
  { id: 'hammer.noise', name: 'Hammer Noise', min: 0, max: 1, default: 0.05, type: 'float' },
  // Amp
  { id: 'amp.drive', name: 'Amp Drive', min: 0, max: 1, default: 0.2, type: 'float' },
  { id: 'amp.tone', name: 'Amp Tone', min: 0, max: 1, default: 0.5, type: 'float' },
  { id: 'amp.level', name: 'Amp Level', min: 0, max: 1, default: 0.8, type: 'float' },
  // Tremolo
  { id: 'tremolo.enabled', name: 'Tremolo On', min: 0, max: 1, default: 0, type: 'bool' },
  { id: 'tremolo.rate', name: 'Tremolo Rate', min: 0.1, max: 20, default: 5, unit: 'Hz', type: 'float' },
  { id: 'tremolo.amount', name: 'Tremolo Amount', min: 0, max: 1, default: 0.3, type: 'float' },
  // Chorus
  { id: 'chorus.enabled', name: 'Chorus On', min: 0, max: 1, default: 0, type: 'bool' },
  { id: 'chorus.rate', name: 'Chorus Rate', min: 0.1, max: 10, default: 0.5, unit: 'Hz', type: 'float' },
  { id: 'chorus.amount', name: 'Chorus Amount', min: 0, max: 1, default: 0.3, type: 'float' },
  // Global
  { id: 'global.transpose', name: 'Transpose', min: -24, max: 24, default: 0, unit: 'st', type: 'int' },
  { id: 'global.volume', name: 'Volume', min: 0, max: 1, default: 0.8, type: 'float' },
];

// ============================================================================
// VOICE EVENTS
// ============================================================================

export interface NoteEvent {
  type: 'note-on' | 'note-off';
  note: number;
  velocity: number;
  sampleOffset: number;
  channel?: number;
}

export interface ControlEvent {
  type: 'pitch-bend' | 'mod-wheel' | 'sustain' | 'aftertouch';
  value: number;
  sampleOffset: number;
}

export type ElectricEvent = NoteEvent | ControlEvent;
